name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.py'
      - '**/*.php'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '!**/*.yml'  # Exclude .yml files from triggering the workflow

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          check-latest: false
          update-environment: true
          allow-prereleases: false

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Extract diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.patch
          cat diff.patch

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          FILE_PATTERN: '**/*.{js,jsx,ts,tsx,py,php}'
          MODEL: 'deepseek/deepseek-r1-distill-llama-70b:free'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "Starting code review process..."
          python -m code_review.main 