name: Code Review

on:
  pull_request:
    paths:
      - '**/*.py'  # Adjust for your code language (e.g., .js, .java, .cpp)
      - '**/*.php'  # Added PHP files to trigger the workflow
      - '!**/*.yml'  # Exclude .yml files from triggering the workflow

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Extract diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.patch
          cat diff.patch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install parse-diff  # Added for parsing git diffs
          pip install PyGithub requests

      - name: Generate review payload
        run: |
          # Create __init__.py files for the package structure
          mkdir -p code_review/github_client code_review/parsers code_review/guidelines code_review/cli code_review/stats code_review/utils code_review/config
          touch code_review/__init__.py
          touch code_review/github_client/__init__.py
          touch code_review/parsers/__init__.py
          touch code_review/guidelines/__init__.py
          touch code_review/cli/__init__.py
          touch code_review/stats/__init__.py
          touch code_review/utils/__init__.py
          touch code_review/config/__init__.py
          
          # Install the local package in development mode
          pip install -e .
          
          # Use the refactored code to generate payload
          python -c "
          from code_review.guidelines.selector import GuidelinesSelector
          from code_review.utils.config_loader import REVIEW_CONFIG
          import json
          
          with open('diff.patch', 'r') as f:
              diff_content = f.read()
          
          selector = GuidelinesSelector()
          payload = selector.create_review_payload(diff_content, REVIEW_CONFIG['review_prompt'])
          
          with open('payload.json', 'w') as f:
              json.dump(payload, f)
          "

      - name: Send diff to AI for review
        run: |
          # Send to OpenRouter
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.OPENROUTER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @payload.json \
            https://openrouter.ai/api/v1/chat/completions > review.json
          
          # Show the response for debugging
          cat review.json

      - name: Post review comments
        run: python -m code_review.cli.post_comments review.json --suggest-changes --inline-comments --create-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}

      - name: Cache review stats
        uses: actions/cache@v3
        with:
          path: ./review_stats.json
          key: ${{ github.repository }}-pr-${{ github.event.pull_request.number }}-stats
          restore-keys: |
            ${{ github.repository }}-pr-${{ github.event.pull_request.number }}-

      - name: Generate review statistics
        if: always()  # Run even if previous steps fail
        run: python -m code_review.cli.generate_stats review.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
