name: Code Review

on:
  pull_request:
    paths:
      - '**/*.py'  # Adjust for your code language (e.g., .js, .java, .cpp)

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Extract diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.patch
          cat diff.patch

      - name: Send diff to AI for review
        run: |
          # Create a proper JSON payload with proper escaping
          echo '{
            "model": "deepseek/deepseek-r1-distill-llama-70b:free",
            "messages": [
              {
                "role": "system",
                "content": "You are an experienced senior developer providing code review feedback. Your comments should be clear, specific, and educational. Include a variety of comment types: clarification requests, alternative approaches, potential bug warnings, style suggestions, and positive reinforcement. For each comment, specify the line number, explain the reasoning, and provide concrete suggestions when applicable."
              },
              {
                "role": "user",
                "content": "Please review the following code and provide detailed, constructive code review comments that follow these patterns:\\n\\n1. Requesting clarification (e.g., \\"Could you explain how this function handles null values?\\")\\n2. Suggesting alternative approaches (e.g., \\"Consider using a Map here to eliminate nested loops\\")\\n3. Highlighting potential bugs (e.g., \\"This might cause an exception if the list is empty\\")\\n4. Suggesting style improvements (e.g., \\"Adding spaces would improve readability\\")\\n5. Commending good work (e.g., \\"Nice job with this refactoring\\")\\n\\nMake sure each comment references specific line numbers, explains why the change matters, and offers concrete suggestions when appropriate.\\n\\nHere'\''s the code to review:\\n\\n'"$(cat diff.patch | jq -sR .)"'"
              }
            ]
          }' > payload.json
          
          # Send to OpenRouter
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.OPENROUTER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @payload.json \
            https://openrouter.ai/api/v1/chat/completions > review.json
          
          # Show the response for debugging
          cat review.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Post review comments
        run: python post_comments.py review.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
