name: Code Review

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.go'
      - '**/*.java'
      - '**/*.rb'
      - '**/*.php'
      - '**/*.cs'
      - '!**/*.test.*'
      - '!**/*.spec.*'
      - '!**/*.yml'
      - '!**/*.md'

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install openai  # For AI review integration

      - name: Run code review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_BRANCH: ${{ github.event.pull_request.base.sha }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # If using OpenAI
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}  # If using OpenRouter
        run: |
          # Create a Python script to run the async code
          cat > run_review.py << 'EOL'
          import asyncio
          from code_review.main import main
          
          if __name__ == "__main__":
              asyncio.run(main())
          EOL
          
          # Run the review
          python run_review.py

      - name: Upload review artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-results
          path: |
            *.log
            *.json
          retention-days: 5
