name: Code Review

on:
  pull_request:
    paths:
      - '**/*.py'  # Adjust for your code language (e.g., .js, .java, .cpp)

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Only need the current commit and its parent
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests jq

      - name: Extract diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.patch
          
      - name: Send diff to AI for review
        id: ai_review
        run: |
          # Create JSON payload with jq for proper escaping
          jq -n --arg diff "$(cat diff.patch)" '{
            "model": "deepseek/deepseek-r1-distill-llama-70b:free",
            "messages": [
              {
                "role": "system", 
                "content": "You are a code reviewer. Be concise and direct. Focus on: 1) Unused code/comments to delete, 2) Code that needs refactoring, 3) Redundant code, 4) Security issues, 5) Performance problems. Use bullet points. Be specific."
              },
              {
                "role": "user", 
                "content": $diff
              }
            ]
          }' > payload.json
          
          # Send to OpenRouter with error handling
          if ! curl -s -S -f -X POST \
            -H "Authorization: Bearer ${{ secrets.OPENROUTER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @payload.json \
            https://openrouter.ai/api/v1/chat/completions > review.json; then
            echo "::error::Failed to get AI review. Check API key and service availability."
            exit 1
          fi

      - name: Post review comments
        run: python post_comments.py review.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
